package com.lantone.icss.trans.yiqian.model;


public class Test {
	
	
	public String getBRXX1001Response() {
		// TODO Auto-generated method stub
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+"<root>"
		+"<head>"
		+"<ErrCode>0</ErrCode>"
		+"<ErrMsg>s_ok</ErrMsg>"
		+"</head>"
		+"<body>"
		+"<Detail>"
		+"<BRDAXM>张3</BRDAXM>"
		+"<BRDAXB>1</BRDAXB>"
		+"<BRCSRQ>1928-01-01</BRCSRQ>"
		+"<BRSFZH>371327192801011234</BRSFZH>"
		+"<BRDAMZ>汉</BRDAMZ>"
		+"<BRJZHM>15874158456</BRJZHM>"
		+"<ZZJGDM>D01223</ZZJGDM>"
		+"<BRLBID>1</BRLBID>"
		+"<BRLBMC>自费</BRLBMC>"
		+"<BRXZID>1</BRXZID>"
		+"<BRXZMC>自费</BRXZMC>"
		+"<BRLXDH>15381192742</BRLXDH>"
		+"<BRLXDZ>浙江省杭州市老年公寓</BRLXDZ> </Detail>"
		+"</body>"
		+"</root>";

	}

	public String getBRXX1002Response() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+"<root>"
			+"<head>"
				+"<ErrCode>0</ErrCode>"
				+"<ErrMsg> </ErrMsg>"
			+"</head>"
			+"<body>"
				+"<Detail>"
					+"<BRJZXH>123122</BRJZXH>"
					+"<ZZJGDM>1002</ZZJGDM>"
					+"<ZZJGMC>医院</ZZJGMC>"
					+"<BRJZRQ>2016-10-13</BRJZRQ>"
					+"<BRDAID>5</BRDAID>"
					+"<BRJZID>4</BRJZID>"
					+"<BRDAXM>王五</BRDAXM>"
					+"<BRJZHM>1012312</BRJZHM>"
					+"<BRCSRQ>1972-01-09</BRCSRQ>"
					+"<BRJZNL>44</BRJZNL>"
					+"<BRNLDW>岁</BRNLDW>"
					+"<BRZZDW>地址</BRZZDW>"
					+"<BRLXDH>13958467903</BRLXDH>"
					+"<BRDAXB>1</BRDAXB>"
					+"<JZKSSJ>2015-10-13</JZKSSJ>"
					+"<JZJSSJ>2015-10-13</JZJSSJ>"
					+"<JZKSID>745</JZKSID>"
					+"<JZKSMC>西医骨科</JZKSMC>"
					+"<JZYSID>1352</JZYSID>"
					+"<JZYSXM>王东</JZYSXM>"
					+"<BRJZZD>胸膜炎</BRJZZD>"
				+"</Detail>"
			+"<Detail>"
				+"<BRJZXH>1</BRJZXH>"
				+"<ZZJGDM>1</ZZJGDM>"
				+"<ZZJGMC>医院</ZZJGMC>"
				+"<BRJZRQ>2016-1-1</BRJZRQ>"
				+"<BRDAID>1</BRDAID>"
				+"<BRJZID>1</BRJZID>"
				+"<BRDAXM>马</BRDAXM>"
				+"<BRJZHM>1</BRJZHM>"
				+"<BRCSRQ>1972-01-09</BRCSRQ>"
				+"<BRJZNL>44</BRJZNL>"
				+"<BRNLDW>岁</BRNLDW>"
				+"<BRZZDW>地址</BRZZDW>"
				+"<BRLXDH>13958467903</BRLXDH>"
				+"<BRDAXB>1</BRDAXB>"
				+"<JZKSSJ>2015-1-1</JZKSSJ>"
				+"<JZJSSJ>2015-1-1</JZJSSJ>"
				+"<JZKSID>745</JZKSID>"
				+"<JZKSMC>西医骨科</JZKSMC>"
				+"<JZYSID>1352</JZYSID>"
				+"<JZYSXM>王东</JZYSXM>"
				+"<BRJZZD>胸膜炎</BRJZZD>"
			+"</Detail>"
			+"<Detail>"
				+"<BRJZXH>1</BRJZXH>"
				+"<ZZJGDM>1</ZZJGDM>"
				+"<ZZJGMC>医院</ZZJGMC>"
				+"<BRJZRQ>2016-1-1</BRJZRQ>"
				+"<BRDAID>1</BRDAID>"
				+"<BRJZID>1</BRJZID>"
				+"<BRDAXM>马</BRDAXM>"
				+"<BRJZHM>1</BRJZHM>"
				+"<BRCSRQ>1972-01-09</BRCSRQ>"
				+"<BRJZNL>44</BRJZNL>"
				+"<BRNLDW>岁</BRNLDW>"
				+"<BRZZDW>地址</BRZZDW>"
				+"<BRLXDH>13958467903</BRLXDH>"
				+"<BRDAXB>1</BRDAXB>"
				+"<JZKSSJ>2015-1-1</JZKSSJ>"
				+"<JZJSSJ>2015-1-1</JZJSSJ>"
				+"<JZKSID>745</JZKSID>"
				+"<JZKSMC>骨科</JZKSMC>"
				+"<JZYSID>1352</JZYSID>"
				+"<JZYSXM>吴</JZYSXM>"
				+"<BRJZZD>肺炎</BRJZZD>"
				+"<FZZLID>461</FZZLID>"
		+"</Detail>"				
		+"</body>"
	+"</root>";
	}

	public String getBRXX1004Response() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+"<root>"
			+"<head>"
			+"<ErrCode>0</ErrCode>"
			+"<ErrMsg>s_ok</ErrMsg>"
			+"</head>"
			+"<body>"
				+"<Detail>"
				+"<CFJLID>2062</CFJLID>"
				+"<BRCFHM>2062</BRCFHM>"
				+"<BRDAXM>李爱泉</BRDAXM>"
				+"<BRCFLX>中药</BRCFLX>"
				+"<CFKDRQ>2014-02-20 09:02:56</CFKDRQ>"
				+"<CFFYPB>已发药</CFFYPB>"
				+"<KDYSID>22</KDYSID>"
				+"<KDKSID>190</KDKSID>"
				+"<KDKSID>内科</KDKSID>"
				+"<KDYSXM>刘杭卫</KDYSXM>"
				+"<YPPMGG>氯沙坦钾片 50mg*7片</YPPMGG>"
				+"<CFYPDJ>26.89</CFYPDJ>"
				+"<CFYPSL>4</CFYPSL>"
				+"<CFYPJE>107.56</CFYPJE>"
				+"</Detail>"
			+"</body>"
	+"</root>";
	}

	public String getBRXX2005Response() {
		// TODO Auto-generated method stub
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
				+"<root>"
				+"<head>"
				+"<ErrCode>0</ErrCode>"
				+"<ErrMsg>s_ok</ErrMsg>"
				+"</head>"
				+"<body>"
				+"<SCJLID>15968</SCJLID>"
				+"</body>"
				+"</root>";

	}

	public String getYYGH1011Response() {

		return"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
				+"<root>"
				+"<head>"
				+"<ErrCode>0</ErrCode>"
				+"<ErrMsg>s_ok</ErrMsg>"
				+"</head>"
				+"<body>"
				+"<Detail>"
				+"<SFJLID>001</SFJLID>"
				+"<ZZJGDM>1062</ZZJGDM>"
				+"<BRJZHM>001</BRJZHM>"
				+"<BRDAXM>张三</BRDAXM>"
				+"<MZLBID>1</MZLBID>"
				+"<MZLBMC></MZLBMC>"
				+"<GHKSID>301</GHKSID>"
				+"<GHKSMC>内科</GHKSMC>"
				+"<GHYSID>5001</GHYSID>"
				+"<GHYSXM>一一</GHYSXM>"
				+"<BRGHRQ>2015/01/01 00:00:00</BRGHRQ>"
				+"<GHSJLB>1</GHSJLB>"
				+"<BRGHXH>1</BRGHXH>"
				+"<MZLBLX>0</MZLBLX>"
				+"<SFTHPB>0</SFTHPB>"
				+"<DYJLID>211</DYJLID>"
				+"</Detail>"
				+"</body>"
				+"</root>";

	}

	public String getJCXX1002Response() {
		
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
				+"<root>"
				+"<head>"
				+"<ErrCode>0</ErrCode>"
				+"<ErrMsg>s_ok</ErrMsg>"
				+"</head>"
				+"<body>"
				+"<Detail>"
				+"<ZZKSID>002</ZZKSID>"
				+"<ZZKSDM>1062</ZZKSDM>"
				+"<ZZKSMC>外科</ZZKSMC>"
				+"<FLKSID>1</FLKSID>"
				+"<HZSRM1>1</HZSRM1>"
				+"<HZSRM2></HZSRM2>"
				+"<HZSRM3></HZSRM3>"
				+"<KSJSXX></KSJSXX>"
				+"</Detail>"
				+"</body>"
				+"</root>";
	}
}
