package com.lantone.icss.rule

import java.util.List;
import java.util.ArrayList;

import com.lantone.icss.rule.model.IcssObjectInput;
import com.lantone.icss.rule.model.ChiefComplaint;
import com.lantone.icss.rule.model.LabResult;
import com.lantone.icss.rule.model.OtherHistory;
import com.lantone.icss.rule.model.PastMedicalHistory;
import com.lantone.icss.rule.model.VitalSign;
import com.lantone.icss.rule.util.PhraseUtil;

import com.lantone.icss.rule.model.IcssObjectOutput;

//declare any global variables here
global IcssObjectOutput output;

//null
rule "code000001"
	salience 100
	no-loop true
	when
		input: IcssObjectInput(input.getChiefComplaint().getComplaints().get("JBZZ001088") != null || input.getChiefComplaint().getComplaints().get("JBZZ001253") != null) 
	then
		output.getDiagnosisValidateResult().put("code000001", true);
		System.out.println("code000001: " + output.getDiagnosisValidateResult().get("code000001"));
end
